import { Navbar } from '@/components';
import localFont from 'next/font/local';
import './globals.css';

const resoluteNF = localFont({
  src: './Resolute NF.ttf',
  variable: '--font-resolute'
})

const version1 = localFont({
  src: './Version1Int.ttf',
  variable: '--font-version'
})

const AppliedSansPro = localFont({
  src: './AppliedSansPro.ttf',
  variable: '--font-applied-sans'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${resoluteNF.variable} ${version1.variable} ${AppliedSansPro.variable}`}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
